/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package connectfour;

import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author VIVEK
 */
public class Selection extends javax.swing.JPanel {

    /**
     * Creates new form Selection
     */
    JButton selectors[];
    int select = 0, noOfColumns;

    public Selection(BoardBuilder builder) {
        noOfColumns = builder.getCols();
        initComponents();
        setLayout(new GridLayout(1, noOfColumns));
        selectors = new JButton[noOfColumns];
        for (int i = 0; i < noOfColumns; i++) {
            selectors[i] = new JButton();
            add(selectors[i]);
        }
        setMaximumSize(new java.awt.Dimension(100 * noOfColumns, 50));
        setPreferredSize(new java.awt.Dimension(100 * noOfColumns, 50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(400, 50));
        setPreferredSize(new java.awt.Dimension(400, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
